#
# Makefile for the Linux Wireless network device drivers.
#

obj-$(CONFIG_MV8686)		    += mv8686/
obj-$(CONFIG_MV8686_FAC)		+= mv8686.fac/
obj-$(CONFIG_ATHEROS_AR6002)	+= ar6002/
#obj-$(CONFIG_NANO_NRX700)		+= nrx700/
obj-$(CONFIG_BCM4319)	+= bcm4319/
#obj-$(CONFIG_BCM4319_FAC)        += bcm4319.fac/
#obj-$(CONFIG_RALINK_RT3070)		+= rt3070/
#obj-$(CONFIG_BCM43X9)	+= bcm43X9/
obj-$(CONFIG_RTL8192CU)		+= rtl8192c.rk28/
obj-$(CONFIG_RTL8188EUS)		+= rtl8188eu/

