


//PE1
POWER_USE_GPIO, POWER_GPIO_IOMUX, GPIOE_SPI1_SEL_NAME,
IOMUXA_GPIO1_A1237, GPIOPortE_Pin1, GPIO_HIGH

//PF4
POWER_USE_GPIO, POWER_GPIO_IOMUX, GPIOF4_APWM2_MMC0WPT_NAME,
IOMUXB_GPIO1_B5, GPIOPortF_Pin4, GPIO_HIGH

//PF5
POWER_USE_GPIO, POWER_GPIO_IOMUX, GPIOF5_APWM3_DPWM3_NAME,
IOMUXB_GPIO1_B5, GPIOPortF_Pin5, GPIO_HIGH

//PF7
POWER_USE_GPIO, POWER_GPIO_IOMUX, GPIOE_SPI1_SEL_NAME,
IOMUXA_GPIO1_A1237, GPIOPortF_Pin7, GPIO_HIGH

