# ROCKCHIP Platform Support
snd-soc-rockchip-objs := rk28-pcm.o
snd-soc-rockchip-iis-objs := rk28-iis.o

obj-$(CONFIG_SND_ROCKCHIP_SOC) += snd-soc-rockchip.o
obj-$(CONFIG_SND_ROCKCHIP_SOC_IIS) += snd-soc-rockchip-iis.o

# ROCKCHIP Machine Support
snd-soc-wm8988-objs := rk28_wm8988.o
snd-soc-rk1000-objs := rk28_rk1000codec.o
snd-soc-wm8994-objs := rk28_wm8994.o
snd-soc-wm8904-objs := rk28_wm8904.o
snd-soc-es8388-objs := rk28_es8388.o

obj-$(CONFIG_SND_ROCKCHIP_SOC_WM8994) += snd-soc-wm8994.o
obj-$(CONFIG_SND_ROCKCHIP_SOC_WM8988) += snd-soc-wm8988.o
obj-$(CONFIG_SND_ROCKCHIP_SOC_RK1000) += snd-soc-rk1000.o
obj-$(CONFIG_SND_ROCKCHIP_SOC_WM8904) += snd-soc-wm8904.o
obj-$(CONFIG_SND_ROCKCHIP_SOC_ES8388) += snd-soc-es8388.o
