
obj-$(CONFIG_MV8686_FAC) += mv8686_fac.o wifi_power.o wifi_config.o

$(obj)/mv8686_fac.o: $(obj)/mv8686_fac.uu
	@echo "UUDE      mv8686_fac.uu"
	@uudecode $(obj)/mv8686_fac.uu -o $(obj)/mv8686_fac.o


